### ISSUE TITLE
Latest version breaks Late game upgrades

### ISSUE THREAD

**Issue by Sub-Zero1324** [lc-sigurd/CSync#4]
The latest version breaks Late game upgrades.

[Error  : Unity Log] MissingMethodException: Method not found: void CSync.Lib.SyncedInstance`1.add_SyncComplete(System.EventHandler)
Stack trace:
MoreShipUpgrades.Plugin.Awake () (at <4da35b0453aa4c4b99265d13486c8852>:IL_0007)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset:OnEnable()

![CSync](https://github.com/lc-sigurd/CSync/assets/15207720/bd161f5a-747e-4bed-8676-e105b4d9e8b6)

**Comment by Sub-Zero1324** [comment]
Just tested again and the latest version breaks the Late game Upgrades.

**Comment by Xyla28** [comment]
HI, we've encountered the same issue just now upon updating to 4.1.0, but was working fine on 3.1.1. Hopefully it will be fixed soon.

**Comment by unluckyjori** [comment]
I think its https://thunderstore.io/c/lethal-company/p/Evaisa/FixPluginTypesSerialization/ it broke my modpack because it auto installed this.

**Comment by unluckyjori** [comment]
its something with the new update though it broke my modpack

**Comment by Lordfirespeed** [comment]
(Unreleased) v5 contains the features required for LGU to update.
