### ISSUE TITLE
[Feedback but more like Issue] can u remove FixPluginTypesSerialization as dependency?

### ISSUE THREAD

**Issue by CoolLKKPS** [lc-sigurd/CSync#8]
FixPluginTypesSerialization will cause LevelLoader cannot recognize custom moons and dungeons, so can u pls remove this unnecessary mod?

**Comment by CoolLKKPS** [comment]
@Lordfirespeed

**Comment by Lordfirespeed** [comment]
No.

**Comment by CoolLKKPS** [comment]
got it
